### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by enamelizer** [appsoftwareltd/dotnet-licence-key-generator#1]
Trying to clarify the license of this library.

As there is currently no license attributed, and language in the readme talking about a 30 day trial I am assuming this is available via a commercial license?

If it is intended to be used free of charge, please apply a license that allows this, else it cannot legally be used by others in their projects. See https://help.github.com/articles/open-source-licensing/

Thanks!

**Comment by gbro3n** [comment]
Hi there, thanks for pointing this out. The reference to a free trial has been included in error when copying documentation from commercial component. I have updated now, and can confirm that the software is free to use.

**Comment by enamelizer** [comment]
Awesome, the project looks very useful and I am looking at using it in our product.
