### ISSUE TITLE
I am having problems converting the code to VB.NET

### ISSUE THREAD

**Issue by acrolink** [appsoftwareltd/dotnet-licence-key-generator#2]
I have used SharpDevelop to convert the code to VB,NET and I understand that I can use the same dll's that are bundled. Still, I am having issues regarding these lines, after conversion:

[error] Type expected. (BC30182) @ Sample1.Server.ConvertedToVBNet\LicenceServer.vb:19,22 >>
Dim keyGenerator = New PkvLicenceKeyGenerator()

[error] 'keyBytes' is not declared. It may be inaccessible due to its protection level @ \Sample1.Server.ConvertedToVBNet\LicenceServer.vb:22,52 >>
Dim key As String = keyGenerator.MakeKey(userId, keyBytes)

Any help would be highly appreciated.

**Comment by gbro3n** [comment]
I don't think this is something I can help with since it sounds like you have an issue with your application code, rather than the component it's self.
