### ISSUE TITLE
User id is useless

### ISSUE THREAD

**Issue by okansarica** [appsoftwareltd/dotnet-licence-key-generator#3]
The userId field in sample projects is useless, because when checking the license key, userId field is never used. So when i enter the license key to any program, it acceps. The user can copy my program to another computer and can run it with the same serial.

The code taken from your own sample projects and changed a little bit. i accepts the key

 int userId = int.Parse(Console.ReadLine());

```
        // We will use the LicenceServer project in this sample to generate a key.
        // In production code, the licence server mechanism would be a separate application
        // from the application that verifies the key. This is important so as to protect the
        // full KeyByteSet array that was used to generate the key.

        var licenceServer = new LicenceServer();

        // Generate the licence key using the seed

        string licenceKeyStr = licenceServer.GenerateLicenceKey(userId);

        Console.WriteLine("\nLicence key generated: " + licenceKeyStr);
        Console.WriteLine("\nNow we will verify the licence key. Please type the licence key printed above: ");

        var result = PkvLicenceKeyResult.KeyInvalid;

        while (result != PkvLicenceKeyResult.KeyGood)
        {
            string userEnteredLicenceKeyStr = licenceServer.GenerateLicenceKey(1);
            Console.WriteLine(userEnteredLicenceKeyStr);
                //Console.ReadLine();

            var pkvKeyCheck = new PkvKeyCheck();

            // Here we recreate a subset of the full original KeyByteSet array that
            // was used to create the licence key. Note the argument to keyByteNo in 
            // each matches that in the full KeyByteSet array.

            var keyBytes = new[] {

                new KeyByteSet(5, 165, 15, 132), 
                new KeyByteSet(6, 128, 175, 213)
            };

            result = pkvKeyCheck.CheckKey(userEnteredLicenceKeyStr, keyBytes, 8, null);

            if (result != PkvLicenceKeyResult.KeyGood)
            {
                Console.WriteLine("\nResult is: " + result.ToString() + ". Please try again.");
            }
        }
```

**Comment by gbro3n** [comment]
You've misunderstood the use of a user ID here. The user ID is simply a seed value. It is not intended to link a licence to a user, it only demonstrates that using the same seed value along with a given set of key values will produce the same licence key. 

What it sounds like you are trying to achieve could still be accomplished by building functionality to have the distributed program send the entered key and seed value to a remote application that regenerates the key with the given seed to check that they match.

_Example_ 
- A user with ID '1234' enters licence key 'ABCDEF'.
- Your program calls to a server with this ID and key. If the server generates the same key for the ID '1234', then you know that the key they have entered was in fact generated for their user ID.

Remember that this is a 'phone home', which this project helps to avoid where not desired - the samples only aim to check that the licence key entered was generated by you, not who it was generated for. However using a solution as I've described above you can add in an additional layer of defence to help you verify that key's are not reused.
