### ISSUE TITLE
Random() in test

### ISSUE THREAD

**Issue by azygis** [appsoftwareltd/dotnet-licence-key-generator#4]
Just a small issue I noticed on your .Tests project.

You are creating new instances of Random **inside** loop. That will not generate random number each loop. You can see that yourself by outputting your seed to console. Right now it would generate 100-200 unique seeds instead of 10000, what the loop tries to do.

To fix the issue, you have to instantiate Random **outside** of your loop and use the reference inside, that will guarantee new seed each time.

**Comment by marcelo2108** [comment]
hello hitas
can you upload the correction?
thank you.-

**Comment by ajtruckle** [comment]
Has this been resolved?

**Comment by gbro3n** [comment]
This has now been fixed in both the new .NET Standard version and legacy version tests.
