### ISSUE TITLE
blacklisting seeds

### ISSUE THREAD

**Issue by DevilDog2098** [appsoftwareltd/dotnet-licence-key-generator#7]
So far i love the generator but im running into an issue adding seeds to the blacklisted seeds array. I added them to a List<string> and convert to an array in the blackListedSeeds call. Key is still showing valid. Any suggestions?

**Comment by BlondeMambaSoftware** [comment]
Note that the blacklisted seeds must be represented as a HEX STRING, so if your blacklisted seed is 12648430, you must provide it as "C0FFEE".
