### ISSUE TITLE
10.2  benefit - maybe is weeknes of your approach

### ISSUE THREAD

**Issue by mzayarnyuk** [appsoftwareltd/dotnet-licence-key-generator#9]
not sure what think othe rbut I think is weak part of your solutions....
"Light weight and fast code execution, tested up to 1,000,000 key generation and verification cycles in 10.2 seconds."

**Comment by gbro3n** [comment]
Yes you are correct, speed of generation / verification potentially lends it's self to easier brute force attacks. This library is suitable for specific use cases - short, quick for humans to enter codes that do not require communication with a remote server. Public / private key based verification is a more robust means of protecting against brute force attacks, depending on your needs.
